apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  MYSQL_DATABASE: c3FJMDE=           # Base64 encoded value of "SQI01"
  MYSQL_USER: dXNlcjE=               # Base64 encoded value of "user1"
  MYSQL_PASSWORD: cGFzc3dvcmQ=       # Base64 encoded value of "password"
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQxMjM= # Base64 encoded value of "password123"