apiVersion: v1
kind: Pod
metadata:
  name: yellow
spec:
  containers:
  - name: lemon
    image: busybox
    command: ["sleep", "3600"]  # Keeps the container running
  - name: gold
    image: redis
    ports:
    - containerPort: 6379