apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /var/log/nginx
      name: claim-log-1
  volumes:
  - name: claim-log-1
    persistentVolumeClaim:
      claimName: claim-log-1