apiVersion: v1
kind: Pod
metadata:
  name: red
spec:
  initContainers:
  - name: init-sleep
    image: busybox
    command: ["sleep", "20"]
  containers:
  - name: redis
    image: redis
    ports:
    - containerPort: 6379
